import { Activity, DEFAULT_PLAYER, Player, Quest } from './types';
const DB_NAME='system-web-db'; const DB_VERSION=2; const STORES={player:'player',quests:'quests',activity:'activity'} as const; const PLAYER_KEY='main';
function requestToPromise<T>(r:IDBRequest<T>):Promise<T>{return new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORES.player))db.createObjectStore(STORES.player);if(!db.objectStoreNames.contains(STORES.quests)){const s=db.createObjectStore(STORES.quests,{keyPath:'id'});s.createIndex('dateKey','dateKey',{unique:false});}if(!db.objectStoreNames.contains(STORES.activity)){const s=db.createObjectStore(STORES.activity,{keyPath:'id'});s.createIndex('timestamp','timestamp',{unique:false});}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function loadPlayer():Promise<Player>{const db=await openDb();const result=await requestToPromise(db.transaction(STORES.player,'readonly').objectStore(STORES.player).get(PLAYER_KEY));if(!result){await savePlayer(DEFAULT_PLAYER);return DEFAULT_PLAYER;}const saved=result as Partial<Player>;return {...DEFAULT_PLAYER,...saved,stats:{...DEFAULT_PLAYER.stats,...(saved.stats??{})},completedWorkoutIds:saved.completedWorkoutIds??[],totalWorkoutCount:typeof saved.totalWorkoutCount==='number'?saved.totalWorkoutCount:0,hp:typeof saved.hp==='number'?saved.hp:100,maxHp:typeof saved.maxHp==='number'?saved.maxHp:100,dailyXpDate:saved.dailyXpDate??null,dailyXpEarned:typeof saved.dailyXpEarned==='number'?saved.dailyXpEarned:0,achievementIds:saved.achievementIds??[],unlockedTitleIds:saved.unlockedTitleIds??[],equippedTitleId:saved.equippedTitleId??null,skillIds:saved.skillIds??[],coins:typeof saved.coins==='number'?saved.coins:0,goals:saved.goals??[],notificationEnabled:saved.notificationEnabled??true};}
export async function savePlayer(p:Player):Promise<void>{const db=await openDb();await requestToPromise(db.transaction(STORES.player,'readwrite').objectStore(STORES.player).put(p,PLAYER_KEY));}
export async function loadQuests(dateKey:string):Promise<Quest[]>{const db=await openDb();return await requestToPromise(db.transaction(STORES.quests,'readonly').objectStore(STORES.quests).index('dateKey').getAll(dateKey)) as Quest[];}
export async function saveQuests(qs:Quest[]):Promise<void>{const db=await openDb();const tx=db.transaction(STORES.quests,'readwrite');qs.forEach(q=>tx.objectStore(STORES.quests).put(q));await new Promise<void>((res,rej)=>{tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error);});}
export async function addActivity(a:Activity):Promise<void>{const db=await openDb();await requestToPromise(db.transaction(STORES.activity,'readwrite').objectStore(STORES.activity).put(a));}
export async function loadRecentActivity(limit=100):Promise<Activity[]>{const db=await openDb();return new Promise((resolve,reject)=>{const r=db.transaction(STORES.activity,'readonly').objectStore(STORES.activity).index('timestamp').openCursor(null,'prev');const rows:Activity[]=[];r.onsuccess=()=>{const c=r.result;if(!c||rows.length>=limit)return resolve(rows);rows.push(c.value as Activity);c.continue();};r.onerror=()=>reject(r.error);});}
